# 1. Importing pandas

In [38]:
import pandas as pd

# 2. Opening a local csv file

In [39]:
df = pd.read_csv('aug_train.csv')
df
# here we are just importing a local file

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# 3. Opening a csv file from an URL

In [40]:
import requests
import pandas as pd
from io import StringIO

# URL of the CSV file hosted online
CSV_URL = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

# Headers are added to mimic a real browser request
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) "
        "Gecko/20100101 Firefox/66.0"
    )
}

# Step 1: Send HTTP GET request to fetch the CSV file
response = requests.get(CSV_URL, headers=HEADERS)

# Step 2: Convert the response text into a file-like object
csv_buffer = StringIO(response.text)

# Step 3: Read the CSV data into a pandas DataFrame
df = pd.read_csv(csv_buffer)

# Display the DataFrame
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

# 4. Sep Parameter

In [41]:
import pandas as pd

# Path to the TSV (Tab-Separated Values) file
FILE_PATH = "movie_titles_metadata.tsv"

# Column names for the dataset
COLUMN_NAMES = [
    "sno",
    "name",
    "release_year",
    "rating",
    "votes",
    "genres"
]

# Read the TSV file into a pandas DataFrame
df = pd.read_csv(
    FILE_PATH,
    sep="\t",              # TSV files use tab as separator
    names=COLUMN_NAMES     # Explicitly assign column names
)

# Display the DataFrame
df

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# 5. Index_col parameter

In [42]:
import pandas as pd

# Load CSV file and set 'enrollee_id' as the DataFrame index
df = pd.read_csv(
    "aug_train.csv",
    index_col="enrollee_id"
)

df

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# 6. Header parameter

In [43]:
pd.read_csv('test.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [44]:
import pandas as pd

# Read CSV file where column names are on the second row
df = pd.read_csv(
    "test.csv",
    header=1
)

df

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

# 7. use_cols parameter

In [45]:
# Whenever we are interested in only specific columns to be included or excluded then we use this parameter

pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

# 8. Squeeze parameters

In [46]:
import pandas as pd

# Read only the 'gender' column from the CSV file
gender_series = pd.read_csv(
    "aug_train.csv",
    usecols=["gender"],
    squeeze=True
)

gender_series



# but in latest pandas this code doesnot work so another snippet is below it to analyse the squeeze param

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [ ]:
import pandas as pd

# Read only the 'gender' column
gender_series = pd.read_csv(
    "aug_train.csv",
    usecols=["gender"]
)["gender"]

gender_series

# 9. Skiprows/nrows Parameter

In [ ]:
import pandas as pd

# Load the entire CSV file into a DataFrame
df = pd.read_csv("aug_train.csv")

df

In [ ]:
pd.read_csv('aug_train.csv',skiprows=[0,3])

In [ ]:
pd.read_csv('aug_train.csv',nrows=100)

# 10. Encoding parameter

In [ ]:
pd.read_csv('zomato.csv',encoding='latin-1')

# 11. Skip bad lines

In [ ]:
pd.read_csv('BX-Books.csv', sep=';', encoding="latin-1",error_bad_lines=False)
# jis line me gadbad hota h usko skip kar dega yhe paramqeter

# 12. dtypes parameter

In [ ]:
pd.read_csv('aug_train.csv',dtype={'target':int}).info()
# overriding the datatype of the columns of the for example

# 13. Handling Dates

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv').info()

In [ ]:
# ab ye date ko object smjh rha h so hum isko parse karke date bana skte hai
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

# Renaming

In [ ]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [ ]:
rename("Royal Challengers Bangalore")

# 14. Convertors

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv')

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename})

# 15. na_values parameter

In [ ]:
pd.read_csv('aug_train.csv',na_values=['Male',])

# 16. Loading a huge dataset in chunks

In [ ]:
aug=pd.read_csv('aug_train.csv')
aug

In [ ]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)

In [ ]:
for chunk in dfs:
    print(chunk.shape)